### ISSUE TITLE
Bug: Does not work with whitepaces in Path

### ISSUE THREAD

**Issue by roalter** [t3hnar/CmdSupport#17]
Both for **Execute cmd Shell** and **Execute cmd script** it only opens a new command line Shell in the matching Directory.

**Comment by roalter** [comment]
Does happen when whitespaces are in the path to the Project.

Please fix it! (Issue on Windows Systems when Double-Quoting Batch-Files)

**Comment by roalter** [comment]
Proposed fix in **actions/RunCmdScriptAction.scala**:

Change (line 19):
```scala
Runtime.getRuntime.exec(Array("cmd", "/c", "start", path), null, new File(file.getParent.getPath))
```

to:
```scala
Runtime.getRuntime.exec(Array("cmd", "/c", "start", "Execute Shell", path), null, new File(file.getParent.getPath))
```

If the program Parameter (path) contains double quotes, it's understood as title of the window.
See: http://stackoverflow.com/questions/7248405/java-execute-cmd-c-start-path-with-spaces-program-exe (solution is not correct there).

I've tested it with a Batch file in two directories, one **with** spaces, the other **without**.

```batch
:: works as expected:
cmd /c start WithoutSpace\test.bat
:: does not work:
cmd /c start "WithoutSpace\test.bat"
cmd /c start "With Space\test.bat"

:: does work as expected:
cmd /c start "Console" "WithoutSpace\test.bat"
cmd /c start "Console" "With Space\test.bat"
cmd /c start "Console" WithoutSpace\test.bat
```

**Comment by t3hnar** [comment]
will release soon.
