### ISSUE TITLE
Incorrect "exists" keyword provided by AutoComplete

### ISSUE THREAD

**Issue by RealEnigma** [t3hnar/CmdSupport#18]
After a painfully substantial amount of debugging, I discovered that the plug-in inserts a keyword "exists" when the correct keyword is "exist".

Thanks.

**Comment by t3hnar** [comment]
hi @RealEnigma, thanks for effort, are you going to create pull request?

**Comment by RealEnigma** [comment]
It was all I could do to find my way here! LOL! I don't know what a pull request is. So I guess the appropriate response is "no." :-)

**Comment by t3hnar** [comment]
It is much easier then you can imagine: https://help.github.com/articles/creating-a-pull-request
:)

**Comment by RealEnigma** [comment]
Since I know nothing about GitHub, it requires more time than I have right now. Are you the developer of the plug-in? If so, maybe you could create the "pull request."

Many thanks!

**Comment by t3hnar** [comment]
ok ok :) I will.

**Comment by RealEnigma** [comment]
Thank you, my friend. :-)
